language: go

go:
  - 1.11.x # This uses automatically the latest version of go

install:
  - mkdir $HOME/src
  - cd $HOME/src
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - git checkout v0.54.0
  - go install --tags extended

script:
  - cd $TRAVIS_BUILD_DIR 
  - rm -rf public || exit 0
  - hugo # This commands builds your website on travis
  - echo 'blog.secondstate.io' > public/CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
